### ISSUE TITLE
Create print style sheet

### ISSUE THREAD

**Issue by yatil** [w3c/wai-website#102]
- [x] Text formatting
- [x] Hiding unnecessary elements
- [x] Format elements for print
- [x] Show URLs inline
- [x] Add to theme

(opened because this issue remembered me: https://github.com/w3c/wai-bcase/issues/30)

**Comment by yatil** [comment]
@slhenry About to implement the print CSS in the main stylesheet. A [live preview](https://w3c.github.io/wai-website-components/components/preview/example-generic.html) is available and also a [PDF preview](https://github.com/w3c/wai-website/files/2273707/print.pdf).

I think this is good to ship for now and then iterated if we see further work necessary.

**Comment by slhenry** [comment]
Looks good on quick skim -- but I can't review in detail now.

Could you list how things were handled and what things are include or not included, e.g.,
* Includes W3C logo, WAI "logo/wordo", breadcrumb
* Does not include main navigation or secondary navigation
* Includes page footer
* Does not include site footer  **_<-- Actually an issue with that is that that is where the copyright statement is.[*] I think print version needs the copyright. Also I think would be nice to have the tagline at the bottom of the print version -- and fine to repeat "W3C Web Accessibility Initiative (WAI)" at the bottom, too. Would it be not too hard to include the site footer minus the links "Contact WAI ... Resources for Roles"?_**
* Writes out URIs for all links
* @@ other

I think fine to implement the print CSS now, *and* send a review opportunity to EOWG and WAI Team (like you did for the show-hide top bit).

_[*] I started to improve that sentence, then decided to leave it since I think it's the only time in my life that I've written "that is that that is" ;-)_

**Comment by yatil** [comment]
Basically that’s what I did, other notable things:

* Changed colors to (mostly) black and white

I’ll make sure to include the site footer for the copyright stuff, good call!

**Comment by yatil** [comment]
fixed in https://github.com/w3c/wai-website-theme/commit/c89666ef0749e7960592b036817cd8ce07ac3ecf
