### ISSUE TITLE
[low] same image in multiple places

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#133]
Where we use the same image in multiple places, it would be good to have the image in one location.

Use case: I updated the last image on [this page](https://www.w3.org/WAI/fundamentals/components/)... but didn't think about it being elsewhere  -- and only later realized that I needed to do a separate update for the same image at the bottom of [this page](https://www.w3.org/WAI/standards-guidelines/).

**Comment by yatil** [comment]
This is by design. It means multiple images in a few cases but gives us a better separation of concerns. Otherwise, one person might change an image that another person did not want to change in their resources because they refer to a specific thing that then changes without anyone being notified (because it is in a different repository).
