### ISSUE TITLE
[Change Text Size or Colors link] Consider making it larger on focus or hover

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#84]
[from Wayne](https://lists.w3.org/Archives/Public/w3c-wai-ig/2018AprJun/0065.html):

> 

Regarding text size and color: I think the "resize text and color" page unit should start with a very large print item says how to use this page if you cannot see the print right now as you try to read this page. Otherwise the users are in a trap. Also the link resize and color should get bigger on focus or hover. There is the very real problem of not being able to see the link on entry to the page. The first time I encountered this (way back when) I was very frustrated because it didn't help me. Do you see? There are two problems: 1) finding the make text large in the first place and 2) Being able to read the page once you get there.

[ suggestions on the page itself covered in https://github.com/w3c/wai-customize-design/issues/2 ]

**Comment by yatil** [comment]
I resize the text when it’s tabbed or focused, see here: https://w3c.github.io/wai-website-components/components/preview/example-home.html 

Some caveats:

- It only really works well on desktop – on mobile there is no :hover and :focus, or the text might be cut off when the item is active.
- I decided to use a technique that does not reflow the rest of the page because that can lead to bad jumping around, especially on mobile.
- I wonder if that helps with Wayne’s main frustration points: “1) finding the make text large in the first place and 2) Being able to read the page once you get there.” I don’t think the audience of the customize page are people with severe low vision, but people who think they have an okay vision but want to change the text size just a bit. People with severe low vision probably have already ways to customize their web experience.

rel: https://github.com/w3c/wai-website-components/commit/3d9220eaf05e2427b33e81297c851e3fbeac730b

**Comment by yatil** [comment]
After looking at it, Shawn and I determined that it is odd and that we might not want that solution.
