### ISSUE TITLE
indicator for off WAI site design

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#88]

**Comment by yatil** [comment]
Use `{% include_cached icon.html name="external-link" label="External Site" %}` – You can set the label to whatever you want. (Unless we want to change have a different icon for different use cases.) The icon is already used in the policies: https://www.w3.org/WAI/policies/australia/

**Comment by slhenry** [comment]
Cool.

We previously had 2:
1. off WAI design (but still on W3C site)
2. off W3C site all together

Let's get some input on whether we want both or not.

Also, whether or not to include them in the navigation. (I am "jarred" a bit when I go off WAI site design from main nav... but maybe that won't happen much when we're done more integrating the "microsites"?)

**Comment by yatil** [comment]
I would be for including it into the navigation – it’s also a simple change. Which I have just implemented. (needs updated data in the navigation.yaml file)

I personally only remember the one with the arrow, and there has been one with a window for pages opening in separate windows, but we don’t do that on the new site.

**Comment by yatil** [comment]
> needs updated data in the navigation.yaml file

Done in 9008c758e7505bbe5d9ccd07b8d71b453ee580fc.

**Comment by slhenry** [comment]
Here are the two we had before (not for opening in separate window):

<img width="233" alt="off-links" src="https://user-images.githubusercontent.com/6991814/40500248-ca9451da-5f49-11e8-86b5-49ec25816e3c.png">

**Comment by yatil** [comment]
Hm. I wonder if anyone understood the first one in context (not having this text available)… Let’s think about it for a bit.

**Comment by slhenry** [comment]
I see some stayed there https://www.w3.org/WAI/test-evaluate/conformance/

**Comment by yatil** [comment]
Yes, some survived the transition. Yay for never changing URLs! :-D

**Comment by yatil** [comment]
@slhenry I thought a bit about this. Currently we are using this icon for external/different context links:

https://w3c.github.io/wai-website-components/components/detail/icons--external-link.html

I think we should keep it for different context links because it says “You stay inside but go somewhere else” (because the arrow is inside the square). 

There are a few options for external links:

* ![](https://user-images.githubusercontent.com/58862/42872251-b3e4f8b4-8a7c-11e8-855b-d79708681ce1.png) Exit style: https://thenounproject.com/search/?q=external%20link&i=25402
* ![](https://user-images.githubusercontent.com/58862/42872280-cfefb2d8-8a7c-11e8-9bff-01748d0bbc10.png) On/Off tilted style: https://thenounproject.com/search/?q=external%20link&i=844188 (my personal preference)
* ![](https://user-images.githubusercontent.com/58862/42872296-da752832-8a7c-11e8-8fe7-6523eb4030ce.png) On/Off straight style: https://thenounproject.com/search/?q=external%20link&i=1241069
* ![](https://user-images.githubusercontent.com/58862/42872317-e75d3e0e-8a7c-11e8-99f6-624c9fbd3818.png) Chain icon: https://thenounproject.com/search/?q=external%20link&i=1525476
