### ISSUE TITLE
EOWG closed updates

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-website#893]
### Resource URL

https://www.w3.org/WAI/about/groups/

### Description

* [x] In [Groups page](https://www.w3.org/WAI/about/groups/), move EOWG to the first list item under Previous Groups
* [x] Add 'Closed: ' to title & h1 (or, provide another suggestion)<br> and under the h1, a box with a link [Accessibility education and outreach: Another milestone in W3C's 30-year history and evolution](https://www.w3.org/blog/2024/accessibility-education-and-outreach-another-milestone-in-w3cs-30-year-history-and-evolution/)
  * [x] https://www.w3.org/WAI/about/groups/eowg/
  * [x] https://www.w3.org/WAI/about/groups/eowg/participate/
  * [x] others?
* [x] remove all EOWG pages from the main nav

### Resource Shortname

wai-groups

**Comment by remibetin** [comment]
> Add 'Closed: ' to title & h1 (or, provide another suggestion)
and under the h1, a box with a link [Accessibility education and outreach: Another milestone in W3C's 30-year history and evolution](https://www.w3.org/blog/2024/accessibility-education-and-outreach-another-milestone-in-w3cs-30-year-history-and-evolution/)

I suggest to use the ["archived" document note](https://wai-website-theme.netlify.app/components/document-notes/archived/). It automatically adds "Archived" to title and h1, and allows to add a custom message.

See previews:
- [[Archived] Education and Outreach Working Group (EOWG)](https://deploy-preview-895--wai-website.netlify.app/about/groups/eowg/)
- [[Archived] Participating in the Education and Outreach Working Group (EOWG)](https://deploy-preview-895--wai-website.netlify.app/about/groups/eowg/participate/)
- [[Archived] Education and Outreach Working Group (EOWG) Participants](https://deploy-preview-894--wai-website.netlify.app/about/groups/eowg/participants)

> remove all EOWG pages from the main nav

I suggest to hide those pages instead of removing them. That way, when users access one of those pages, they can see it is part of the "WAI Groups" section of the site, and the breadcrumb works.
