### ISSUE TITLE
[News] ability to search all easily - maybe all on one page

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-website#96]
(can discuss as needed)

**Comment by yatil** [comment]
You want the ability to have a separate search for news articles? They are already included in the general site search.

**Comment by slhenry** [comment]
For my use cases: I'd like to be able to get all News on one page and I'd do a find-in-page.

**Comment by yatil** [comment]
So that would be a personal feature for you? Then we don’t need to have that on the website (but could live on GitHub), I think. I don't feel that this is a use case for anyone and we already have the paged news archive. Otherwise, we would force people that want to share only one news story to download a potentially multiple megabyte big document. I think we would be better served with multiple ways to filter news and other content on the website over the long run.

**Comment by slhenry** [comment]
It seems that a few other people will want all the news on one page for some use cases.

I propose that we provide an *option* for that. The paged news archive can be the default. And possibly there is an easy way for people to share only *one* news story without others on the page -- although that seems low priority to me.

Is there any reason not to make that an option available for everyone?

**Comment by yatil** [comment]
All news can now be viewed on one page: https://w3c.github.io/wai-news/news/all/ A link to this one page has been added to the pagination area of the paginated news pages.
